
- name: Create or Destroy EC2 instances and Route53 records
  hosts: all
  connection: local
  

  vars:
    sg_id: "sg-06e8a11e6012588b9"
    ami_id: "ami-0220d79f3f480ecf5"
    domain_name: "vardhineni.online"
    env: "dev"
    action: "create"

    instances:
      - mongodb

  tasks:

    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}-{{ env }}"
        image_id: "{{ ami_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        wait: true

        tags:
          Project: "roboshop"
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output
      when: action == "create"

    - name: Create Route53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
        wait: false
      loop: "{{ ec2_output.results }}"
      when: action == "create"

    - name: Create frontend Route53 record
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
        wait: false
      loop: "{{ ec2_output.results }}"
      when:
        - item.item == "frontend"
        - action == "create"

    ##################################################
    # Destroy Resources
    ##################################################

    - name: Delete frontend Route53 record
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when:
        - item == "frontend"
        - action == "destroy"

    - name: Delete Route53 records
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: action == "destroy"

    - name: Delete EC2 instances
      amazon.aws.ec2_instance:
        state: absent
        name: "{{ item }}-{{ env }}"
        wait: true
      loop: "{{ instances }}"
      when: action == "destroy"












# - name: create ec2 and r53 records
#   hosts: all
#   connection: local
#   vars:
#     sg_id: sg-06e8a11e6012588b9
#     ami_id: ami-0220d79f3f480ecf5
#     domain_name: vardhineni.online
#     instances:
#     - mongodb
#     env: dev

  
#   tasks:
#   - name: create ec2 instance
#     amazon.aws.ec2_instance:
#       instance_type:  "t3.micro"
#       security_group: "{{sg_id}}"
#       image_id: "{{ami_id}}"
#       name: "{{ item }}-{{ env }}"
#       tags:
#         Project: roboshop
#         Component: "{{item}}"
#         Enviornment: "{{env}}"
#         Name : "{{item}}-{{env}}"
#     loop: "{{instances}}"
#     register: ec2_output
#     when: action=="Create"

#   - name : creare r53 records
#     amazon.aws.route53:
#       state: present
#       zone: "{{ domain_name }}"
#       record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # mongodb-dev.daws88s.online, frontend-dev.daws88s.online
#       type: A
#       ttl: 1
#       value: "{{ item.instances[0].private_ip_address }}"
#       wait: false
#       overwrite: true
#     loop: "{{ ec2_output.results }}" # list
#     when: action == "create"

#   - name: create r53 record for frontend
#     amazon.aws.route53:
#       state: present
#       zone: "{{ domain_name }}"
#       record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
#       type: A
#       ttl: 1
#       value: "{{ item.instances[0].public_ip_address }}"
#       wait: false
#       overwrite: true
#     loop: "{{ ec2_output.results }}"
#     when:  # and
#     - item.item == "frontend"
#     - action == "create"

#    ### DESTROY ###
#   - name: delete r53 records for frontend
#     amazon.aws.route53:
#       state: absent
#       zone: "{{ domain_name }}"
#       record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
#       type: A
#       ttl: 1
#     loop: "{{ instances }}"
#     when:  # and
#     - item == "frontend"
#     - action == "destroy"

#   - name: delete r53 records
#     amazon.aws.route53:
#       state: absent
#       zone: "{{ domain_name }}"
#       record: "{{ item }}-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
#       type: A
#       ttl: 1
#     loop: "{{ instances }}"
#     when: action == "destroy"

#   - name: delete ec2 instance
#     amazon.aws.ec2_instance:
#       state: absent
#       name: "{{ item }}-{{ env }}"
#       wait: false
#     loop: "{{ instances }}"
#     when: action == "destroy"